### ISSUE TITLE
Left pane folder traversal loses focus when navigating with arrow keys

### ISSUE THREAD

**Issue by nSpecter** [raspberrypi-ui/pcmanfm-buster#6] opened 2021-01-31 06:31 UTC
Buster 10 / Linux 5.4.83-v7l+ 
PCManFM version unknown. There doesn't appear to be a way to get a version number from the GUI or CLI? (no **Help|About** or **--version** command line option)

**Problem:**

When navigating the folder tree structure in the left pane with arrow keys:

Up-Arrow and Down-Arrow work as expected--the highlighted focus moves up and down the folder hierarchy. The right pane changes to display the contents of the highlighted folder.

Right-Arrow also works as expected. If the highlighted folder has no child folders, nothing occurs. If the highlighted folder does have child folders, it expands the hierarchy. If pressed a second time, it moves focus to the first child and so on and so forth, down the branch.

_Left-Arrow_, however, does not always work as expected:

PCManFM has two behaviors dependent on if you're pressing Left-Arrow on a _parent_ folder of an expanded tree or you're pressing Left-Arrow on a _child_ folder in an expanded tree.

If you press Left-Arrow on any _parent_ folder, it performs as expected and collapses the underlying hierarchy and maintains focus and you can continue navigating the folder hierarchy.

_However,_ if you press Left-Arrow on a **child** folder it will move focus to the parent folder and become stuck. Focus is somehow shifted to the right-hand "folder contents" pane and any further arrow key-presses will be active in that pane. To continue navigating on the left, you have to either hit TAB twice or click on a left-pane folder with the mouse to return focus to the left pane. Only then can you continue navigating with the arrow keys. This makes navigating from a bottom-most child folder to a top-most parent folder impossible.

**Expected Behavior:**

A Left-Arrow on a child folder should move focus to the parent folder. A subsequent Left-Arrow should collapse the folder hierarchy. And so on and so forth, up the tree. Focus should not change between panes unless specifically instructed by the user (TAB key or mouse).

I hope I was able to describe that succinctly. :)

**Comment by spl237** [comment] 2021-01-31 20:00
Interesting. 

The file manager is a mix of standard GTK widgets, and various custom widgets taken from Xfce - I'd hope that GTK would have got the correct behaviour for their directory tree view widget, so I suspect this is a bug in a custom widget. (I did have to fix a bug in another one of the Xfce widgets in the file manager last week...)

I'll have a look over the next few days - if it's a GTK widget, there's not much I'll be able to do, as bug reports to GNOME tend to result in a reply of "it's meant to be like that...", but if it's a custom widget, I should be able to fix it.

**Comment by nSpecter** [comment] 2021-01-31 23:41
[\m/>.<\m/](https://i.imgur.com/TYSSBFL.png)

**Comment by spl237** [comment] 2021-02-01 16:26
Hmmm.

OK, I've just tried this, and I can't repeat the behaviour you describe. I don't get any focus change on left-arrow in the folder tree - it behaves exactly as you suggest it should, either collapsing a folder's children or moving up the tree to the parent. I've tried several different images I had lying around on my desk, and it works correctly on all of them.

So for some reason, yours is behaving differently.

Can you try a clean image and see if the problem is still there? If it is, then I'm wondering if it is something in the file manager configuration which is causing the problem - can you please post the contents of your ~/.config/libfm/libfm.conf and ~/.config/pcmanfm/LXDE-pi/pcmanfm.conf files?

**Comment by nSpecter** [comment] 2021-02-03 03:31
Just a quick note that I was able to duplicate the issue on another Pi with a recently installed Buster 10 aarch64.

I'll get config files uploaded and posted soonest.

**Comment by nSpecter** [comment] 2021-02-05 05:00
Okay, I think I've localized the source of the issue.

It's related to the PCManFM setting "**View As Detailed List"**. Either by selecting it on the toolbar or setting it as the default in preferences.

It doesn't do it if you have "View as icons" or "View as small icons" selected.

I've tested it on an older Buster 10 32bit install I had lying around on an SDCard, my current updated 32bit install, a 64bit install and a brand new 32bit install I downloaded and created today.

Let me know if you still need the .conf files. I have a whole passel of them. :)

But I think the above setting should make the problem exhibit itself on your system.

**Comment by spl237** [comment] 2021-02-05 10:45
Many thanks - yes, that change means I can repeat the problem, so no need for the conf files.

A different widget is used in the right-hand pane for the detailed list view from that used for the three icon views, and my guess would be that it is grabbing keyboard focus when it updates, which in this case it shouldn't do. I'm doing some fiddling with various file manager issues at the moment, so I'll see if I can stomp on the focus-grabbing!

**Comment by nSpecter** [comment] 2021-02-05 17:11
Awesome :)

Do you mind if I add a few more things/suggestions to your list? 

Should I open a ticket for each or just post a list?

**Comment by spl237** [comment] 2021-02-05 17:15
If they are bugs, please post a ticket for each.

If they are suggestions, a single post with all of them would be fine! I can't promise that I'll do anything about suggestions in the near future, as I'm a bit snowed at the moment, but I'd hope to deal with bugs relatively quickly. (The distinction between a bug and a suggestion may, of course, be entirely subjective... ;) )

**Comment by spl237** [comment] 2021-02-10 11:29
OK, I've found the problem. It seems to have been a deliberate decision by the author, but IMHO it's a bad one!

The intention seems to have been to make keyboard text search work automatically on the folder view pane rather than on the directory tree, irrespective of the location of the keyboard focus, but this hasn't been implemented properly, because it only affects the folder view, not the icon view (so is inconsistent anyway). Also, I can't see why it would actually be useful to move the general keyboard focus about underneath the user - as you discovered, that's just confusing.

There is probably a way to achieve what the author wanted to do, but the bodge doesn't do it properly anyway, so I'll just pull it out. I'll do a bit of testing to make sure it hasn't broken anything else before pushing it to apt.

FYI, the bodge is lines 667 to 669 of src/main-win.c; I think it is safe to just remove it completely. The slight concern I have is that there are other similar focus bodges happening in that file (such as the one at lines 206 to 222), so there may be other related issues that we haven't found yet...

**Comment by spl237** [comment] 2021-02-11 14:47
Fix is now in apt - if you do an apt update / apt full-upgrade, the problem should be fixed. Closing now - please reopen if the fix doesn't work for you.

**Closed by spl237** 2021-02-11 14:47 UTC
